[09-20-2022 15:14:57]
  File "/home/msch/Projects/Wordle_Scores_Bot/./run_bot.py", line 29, in submit
    baseStats, status = bot.db.submit_data(
  File "/home/msch/Projects/Wordle_Scores_Bot/./lib/wordle.py", line 549, in submit_data
    raise ValueError


[09-20-2022 15:16:24]
  File "/home/msch/Projects/Wordle_Scores_Bot/./run_bot.py", line 29, in submit
    baseStats, status = bot.db.submit_data(
  File "/home/msch/Projects/Wordle_Scores_Bot/./lib/wordle.py", line 545, in submit_data
    raise TypeError


